version: "3.9"
services:
  weather:
    restart: always
    build: ./apps/weather/server/api
    env_file:
      - weather.env
      - postgres.env
      - secrets.env
    depends_on:
      - postgres
    ports:
      - "3031:3031"
  feedpage:
    restart: always
    build: ./apps/feedpage/server
    env_file:
      - feedpage.env
    ports:
      - "8080:8080"
  postgres:
    restart: always
    image: postgres:11
    env_file:
      - postgres.env
      - secrets.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    restart: always
    build: ./nginx
    depends_on:
      - weather
      - feedpage
      - zabbix-web
    ports:
      - "80:80"
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.2-latest
    restart: always
    depends_on: 
      - postgres
    env_file: 
      - postgres.env
      - secrets.env
      - zabbix.env
    ports:
      - "10051:10051"
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.2-latest
    restart: always
    depends_on: 
      - postgres
    env_file: 
      - postgres.env
      - secrets.env
      - zabbix.env
    ports:
      - "8081:8080"
  backup:
    restart: always
    build: ./backup
    depends_on:
      - postgres
    env_file:
      - postgres.env
      - secrets.env
    volumes:
      - backup:/backup
volumes: 
  postgres:
  backup:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/mnt/raid1/backup"

