version: "3.9"
services:
  grill:
    restart: always
    build: ./apps/grill-logger/server
    env_file:
      - grill.env
      - postgres.env
      - secrets.env
      - grill_secrets.env
    depends_on:
      - postgres
    ports:
      - "8090:8090"
  weather:
    restart: always
    build: ./apps/weather/server/api
    env_file:
      - weather.env
      - postgres.env
      - secrets.env
      - weather_secrets.env
    depends_on:
      - postgres
    ports:
      - "3031:3031"
  feedpage:
    restart: always
    build: ./apps/feedpage/server
    env_file:
      - feedpage.env
    ports:
      - "8080:8080"
  jabba:
    restart: always
    build: ./apps/jabba
    env_file:
      - jabba.env
      - postgres.env
      - secrets.env
      - jabba_secrets.env
    depends_on: 
      - postgres
    ports:
      - "8070:8070"
    volumes: 
      - ./jabba:/config
      - jabba:/data
  mail:
    restart: always
    build: ./apps/mail
    volumes: 
      - mail:/data
      - ./mail:/config
      - /home/ubuntu/.config:/root/.config
      - /home/ubuntu/.gnupg:/root/.gnupg
      - /home/ubuntu/.password-store:/root/.password-store
  githubmirror:
    restart: always
    build: ./apps/githubmirror
    volumes: 
      - githubmirror:/data
      - ./githubmirror:/config
      - /home/ubuntu/.ssh:/root/.ssh
    env_file:
      - githubmirror_secrets.env
  lastpass:
    restart: always
    build: ./apps/lastpass
    volumes: 
      - lastpass:/data
      - ./lastpass:/config
  rclone:
    restart: always
    build: ./apps/rclone
    volumes: 
      - rclone:/data
      - ./rclone:/root/.config/rclone
    env_file: 
      - rclone_secrets.env
  postgres:
    restart: always
    image: postgres:11
    env_file:
      - postgres.env
      - secrets.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    restart: always
    build: ./apps/nginx
    depends_on:
      - weather
      - feedpage
      # - zabbix-web
      - grill
      - jabba
    ports:
      - "80:80"
  # zabbix-server:
  #   image: zabbix/zabbix-server-pgsql:alpine-5.2-latest
  #   restart: always
  #   depends_on: 
  #     - postgres
  #   env_file: 
  #     - postgres.env
  #     - secrets.env
  #     - zabbix.env
  #   ports:
  #     - "10051:10051"
  # zabbix-web:
  #   image: zabbix/zabbix-web-nginx-pgsql:alpine-5.2-latest
  #   restart: always
  #   depends_on: 
  #     - postgres
  #   env_file: 
  #     - postgres.env
  #     - secrets.env
  #     - zabbix.env
  #   ports:
  #     - "8081:8080"
  backup:
    restart: always
    build: ./apps/backup
    depends_on:
      - postgres
    env_file:
      - postgres.env
      - secrets.env
    volumes:
      - backup:/backup
      - /home/ubuntu:/apps
  dns-updater:
    restart: always
    build: ./apps/dns-updater
    env_file: 
      - dns_updater_secrets.env
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVERURL=house.johnjonesfour.com
      - SERVERPORT=51820
      - PEERS=john
      - ALLOWEDIPS=0.0.0.0/0
      - PEERDNS=192.168.1.1
    volumes:
      - ./wiregaurd:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
volumes: 
  postgres:
  jabba:
  backup:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/mnt/raid1/backup"
  mail:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/mnt/raid1/mail"
  githubmirror:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/mnt/raid1/githubmirror"
  lastpass:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/mnt/raid1/lastpass"
  rclone:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/mnt/raid1/cloudarchive"
