version: "3.9"
services: 
  ################################################################################
  # Projects 
  ################################################################################
  weather:
    image: ghcr.io/johnjones4/weather-ship-tango-delta:latest
    restart: always
    env_file:
      - ./config/env/weather.env
      - ./config/env/postgres.env
      - ./config/env/secrets.env
      - ./config/env/weather_secrets.env
    depends_on:
      - postgres
      - jabba-server
    ports:
      - "3031:3031"
  feedpage:
    image: ghcr.io/johnjones4/feedpage:latest
    restart: always
    env_file:
      - ./config/env/feedpage.env
    ports:
      - "8080:8080"
  hal9000:
    image: ghcr.io/johnjones4/hal9000:latest
    restart: always
    depends_on:
      - mosquitto
      - weather
    env_file:
      - ./config/env/hal.env
      - ./config/env/hal_secrets.env
    volumes: 
      - hal9000:/data
    ports:
      - 8050:8050

  ################################################################################
  # Monitoring 
  ################################################################################
  jabba-server:
    restart: always
    image: ghcr.io/johnjones4/jabba-server:latest
    environment:
      - HTTP_HOST=:8070
    env_file:
      - ./config/env/jabba.env
      - ./config/env/jabba_secrets.env
    depends_on: 
      - postgres
    ports:
      - "8070:8070"
    volumes:
      - ./config/jabba:/config
  jabba-loghandler:
    restart: always
    image: ghcr.io/johnjones4/jabba-loghandler:latest
    environment:
      - HTTP_HOST=:8060
    env_file:
      - ./config/env/jabba.env
      - ./config/env/jabba_secrets.env
    depends_on: 
      - jabba-server
    ports:
      - "8060:8060"
    volumes: 
      - ./config/jabba:/config
  jabba-poller:
    restart: always
    image: ghcr.io/johnjones4/jabba-poller:latest
    env_file:
      - ./config/env/jabba.env
      - ./config/env/jabba_secrets.env
    depends_on: 
      - jabba-server
      - weather
      - feedpage
      - nginx
    volumes: 
      - ./config/jabba:/config

  ################################################################################
  # Backup 
  ################################################################################
  mail:
    restart: always
    image: ghcr.io/johnjones4/backup-mail:latest
    env_file: 
      - ./config/env/shared.env
    volumes: 
      - mail3:/data
      - ./config/mail:/config
      - /home/ubuntu/.config:/root/.config
      - /home/ubuntu/.gnupg:/root/.gnupg
      - /home/ubuntu/.password-store:/root/.password-store
    depends_on:
      - jabba-loghandler
  githubmirror:
    restart: always
    image: ghcr.io/johnjones4/backup-githubmirror:latest
    volumes: 
      - githubmirror3:/data
      - ./config/githubmirror:/config
      - /home/ubuntu/.ssh:/root/.ssh
    env_file:
      - ./config/env/githubmirror_secrets.env
      - ./config/env/shared.env
    depends_on:
      - jabba-loghandler
  lastpass:
    restart: always
    image: ghcr.io/johnjones4/backup-lastpass:latest
    volumes: 
      - lastpass3:/data
      - ./config/lastpass:/config
    env_file: 
      - ./config/env/shared.env
    depends_on:
      - jabba-loghandler
  rclone:
    restart: always
    image: ghcr.io/johnjones4/backup-rclone:latest
    volumes: 
      - rclone3:/data
      - ./config/rclone:/root/.config/rclone
    env_file: 
      - ./config/env/rclone_secrets.env
      - ./config/env/shared.env
    depends_on:
      - jabba-loghandler
  backup:
    restart: always
    image: ghcr.io/johnjones4/backup-backup:latest
    depends_on:
      - postgres
      - jabba-loghandler
    env_file:
      - ./config/env/postgres.env
      - ./config/env/secrets.env
      - ./config/env/shared.env
    volumes:
      - backup3:/backup
      - /home/ubuntu:/apps

  ################################################################################
  # Infra 
  ################################################################################
  postgres:
    restart: always
    image: postgres:11
    env_file:
      - ./config/env/postgres.env
      - ./config/env/secrets.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    restart: always
    image: ghcr.io/johnjones4/nginx:latest
    depends_on:
      - weather
      - feedpage
      - jabba-server
      - jabba-loghandler
      - hal9000
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt/live:/certificates
  dns-updater:
    restart: always
    image: ghcr.io/johnjones4/dns-updater:latest
    env_file: 
      - ./config/env/dns_updater_secrets.env
    depends_on:
      - jabba-loghandler
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file: 
      - ./config/env/wireguard.env
    volumes:
      - ./config/wiregaurd:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  mqtt2kasa:
    image: ghcr.io/johnjones4/mqtt2kasa:latest
    restart: always
    volumes:
      - ./config/mqtt2kasa:/usr/src/app/data
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes: 
      - ./config/mosquitto:/mosquitto/config
  
volumes: 
  postgres:
  backup3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/backup"
  mail3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/mail"
  githubmirror3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/githubmirror"
  lastpass3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/lastpass"
  rclone3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/cloudarchive"
  hal9000:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/hal9000"
