version: "3.9"
services:
  weather:
    image: ghcr.io/johnjones4/weather-ship-tango-delta:latest
    restart: always
    env_file:
      - weather.env
      - postgres.env
      - secrets.env
      - weather_secrets.env
    depends_on:
      - postgres
      - jabba-server
    ports:
      - "3031:3031"
  feedpage:
    image: ghcr.io/johnjones4/feedpage:latest
    restart: always
    env_file:
      - feedpage.env
    ports:
      - "8080:8080"
  jabba-server:
    restart: always
    image: ghcr.io/johnjones4/jabba-server:latest
    environment:
      - HTTP_HOST=:8070
    env_file:
      - jabba.env
      - jabba_secrets.env
    depends_on: 
      - postgres
    ports:
      - "8070:8070"
    volumes:
      - ./jabba:/config
  jabba-loghandler:
    restart: always
    image: ghcr.io/johnjones4/jabba-loghandler:latest
    environment:
      - HTTP_HOST=:8060
    env_file:
      - jabba.env
      - jabba_secrets.env
    depends_on: 
      - jabba-server
    ports:
      - "8060:8060"
    volumes: 
      - ./jabba:/config
  jabba-poller:
    restart: always
    image: ghcr.io/johnjones4/jabba-poller:latest
    env_file:
      - jabba.env
      - jabba_secrets.env
    depends_on: 
      - jabba-server
      - weather
      - feedpage
      - nginx
    volumes: 
      - ./jabba:/config
  mail:
    restart: always
    build: ./apps/mail
    env_file: 
      - shared.env
    volumes: 
      - mail3:/data
      - ./mail:/config
      - /home/ubuntu/.config:/root/.config
      - /home/ubuntu/.gnupg:/root/.gnupg
      - /home/ubuntu/.password-store:/root/.password-store
    depends_on:
      - jabba-loghandler
  githubmirror:
    restart: always
    build: ./apps/githubmirror
    volumes: 
      - githubmirror3:/data
      - ./githubmirror:/config
      - /home/ubuntu/.ssh:/root/.ssh
    env_file:
      - githubmirror_secrets.env
      - shared.env
    depends_on:
      - jabba-loghandler
  lastpass:
    restart: always
    build: ./apps/lastpass
    volumes: 
      - lastpass3:/data
      - ./lastpass:/config
    env_file: 
      - shared.env
    depends_on:
      - jabba-loghandler
  rclone:
    restart: always
    build: ./apps/rclone
    volumes: 
      - rclone3:/data
      - ./rclone:/root/.config/rclone
    env_file: 
      - rclone_secrets.env
      - shared.env
    depends_on:
      - jabba-loghandler
  postgres:
    restart: always
    image: postgres:11
    env_file:
      - postgres.env
      - secrets.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    restart: always
    build: ./apps/nginx
    depends_on:
      - weather
      - feedpage
      - jabba-server
      - jabba-loghandler
      - hal9000
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt/live:/certificates
  backup:
    restart: always
    build: ./apps/backup
    depends_on:
      - postgres
      - jabba-loghandler
    env_file:
      - postgres.env
      - secrets.env
      - shared.env
    volumes:
      - backup3:/backup
      - /home/ubuntu:/apps
  dns-updater:
    restart: always
    build: ./apps/dns-updater
    env_file: 
      - dns_updater_secrets.env
    depends_on:
      - jabba-loghandler
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVERURL=house.johnjonesfour.com
      - SERVERPORT=51820
      - PEERS=john
      - ALLOWEDIPS=0.0.0.0/0
      - PEERDNS=192.168.1.1,house.johnjonesfour.com
    volumes:
      - ./wiregaurd:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  mqtt2kasa:
    image: ghcr.io/johnjones4/mqtt2kasa:latest
    restart: always
    volumes:
      - ./mqtt2kasa:/usr/src/app/data
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes: 
      - ./mosquitto:/mosquitto/config
  hal9000:
    image: ghcr.io/johnjones4/hal9000:latest
    restart: always
    depends_on:
      - mosquitto
      - weather
    env_file:
      - hal.env
      - hal_secrets.env
    volumes: 
      - hal9000:/data
    ports:
      - 8050:8050
volumes: 
  postgres:
  backup3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/backup"
  mail3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/mail"
  githubmirror3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/githubmirror"
  lastpass3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/lastpass"
  rclone3:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/cloudarchive"
  hal9000:
    driver_opts:
      type: "nfs"
      o: "addr=files,nolock,soft,rw"
      device: ":/volume1/Apps/hal9000"
