version: "3.9"
services:
  weather:
    restart: always
    build: ./apps/weather/server/api
    env_file:
      - weather.env
      - postgres.env
      - secrets.env
    depends_on:
      - postgres
    ports:
      - "3031:3031"
  postgres:
    restart: always
    image: postgres
    env_file:
      - postgres.env
      - secrets.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    restart: always
    build: ./nginx
    depends_on:
      - weather
    ports:
      - "80:80"
    expose:
      - "80"
volumes: 
  postgres:
